version: '3.8'

services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    healthcheck:
      test: ["CMD", "mongosh", "--eval", "db.adminCommand('ping')"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 30s
    networks:
      - mongodb_network

  mongo-express:
    image: mongo-express:latest
    container_name: mongo-express
    restart: always
    environment:
      # Web interface credentials
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: example
      # MongoDB connection credentials
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
      ME_CONFIG_MONGODB_SERVER: mongodb
    ports:
      - "8081:8081"
    depends_on:
      - mongodb
    networks:
      - mongodb_network

  migrations:
    build:
      context: .
      dockerfile: migrations/Dockerfile
    environment:
      MONGO_ROOT_USERNAME: root
      MONGO_ROOT_PASSWORD: example
      MONGO_PORT: 27017
      MONGO_DB: test
      MONGO_AUTH_SOURCE: admin
    depends_on:
      mongodb:
        condition: service_healthy
    networks:
      - mongodb_network

volumes:
  mongodb_data:
    name: mongodb_data

networks:
  mongodb_network:
    name: mongodb_network 